# The URL the site will be built for
base_url = "https://bastion-falls.thekennel.info"
title = "Bastion Falls"
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "zola_easydocs_theme"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  # Character
  { name = "families", feed = true, render = true },
  { name = "organizations", feed = true, render = true },
  { name = "ethnicities", feed = true, render = true },
  { name = "religions", feed = true, render = false },
  { name = "species", feed = true, render = false },
  { name = "parents", feed = false, render = false },
  { name = "siblings", feed = false, render = false },

  # Location
  { name = "location_type", feed = true, render = true },
  { name = "parent_location", feed = false, render = false},

  # Organization
  { name = "organization_id", feed = false, render = false },
  { name = "organization_type", feed = true, render = false },
  { name = "leaders", feed = false, render = false },
  
  # Ethnicities
  { name = "locations", feed = false, render = false },

  # Event
  { name = "event_type", feed = true, render = false },
  { name = "primary_characters", feed = true, render = false },
  { name = "primary_families", feed = true, render = false },

  # Species
  { name = "creature_type", feed = true, render = false },

  # Misc
  { name = "journal_type", feed = true, render = false },

  { name = "character_id", feed = false, render = true },
  { name = "character_org_id", feed = false, render = false },  
  { name = "location_id", feed = false, render = false },
  { name = "parent_event_id", feed = false, render = false },
  { name = "family_id", feed = false, render = false },
  { name = "family_location_id", feed = false, render = false },
  { name = "parent_location_id", feed = false, render = false },
  { name = "primary_organizations", feed = true, render = false },
]

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
taxonomies = "safe"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[link_checker]
internal_level = "warn"

[search]
include_title = true
include_description = true
include_path = true
include_content = true

# truncate_content_length = 100

[extra]
# Put all your custom variables here
easydocs_heading_threshold = 3
repo = "https://github.com/nicodoggie/bastion-falls"
fantasy_calendar_id = "089e518f9ea966373b1c71535c25b98a"