name: "BF Site"
on: [push,workflow_dispatch]
jobs:
  build-deploy:
    env:
      CLOUDFLARE_ACCOUNT_ID: 42310a8cfd53b541a4579a8af2b1821d
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"
    - name: Yarn Install
      run: yarn install --immutable
    - name: Build Kingraph SVGs
      run: ./kingraph.sh
    - uses: actions/github-script@v6
      with:
        script: |
          const fs = require("fs");
          const commits = ${{ toJSON(github.event.commits) }}
          let changelog = '';
          for (const commit of commits) {
            const { id, author, url, message } = commit;
            changelog += `+++\ntitle = "Changelog"\nweight = 99\n+++\n\n`
            changelog += `Commit ${id} by ${author.username}: ${url}\n\n`;
            changelog += `---\n\n`;
            changelog += `${message.replaceAll(/\]\s+\(/, "](")}\n\n`;
          }
          fs.writeFileSync('content/changelog.md', changelog);
    - name: Upload changelog as artifact
      uses: actions/upload-artifact@v3
      with:
        name: CHANGELOG.md
        path: content/changelog.md
    - name: Build Zola
      uses: shalzz/zola-deploy-action@v0.17.2
      env: 
        BUILD_ONLY: true
    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_KEY }}
        command: pages deploy public --project-name bastion-falls --commit-hash ${{ github.sha }} --branch ${{ github.ref_name }}
    - name: Save CHANGELOG.md as an artifact and link it on Discord
      run: echo -ne "${{ github.event.commits[0].message }}" > content/changelog.md
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.
          See the changes on https://bastion-falls.thekennel.info/changelog/

          
