name: "BF Site"
on: [push,workflow_dispatch]
jobs:
  build-deploy:
    env:
      CLOUDFLARE_ACCOUNT_ID: 42310a8cfd53b541a4579a8af2b1821d
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: PNPM Install
      uses: pnpm/action-setup@v3
      env:
        ENV: ci
      with:
        version: 10
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]
    - name: Build Kingraph SVGs
      run: ./kingraph.sh
    - uses: actions/github-script@v7
      with:
        script: |
          const fs = require("fs");
          const commits = ${{ toJSON(github.event.commits) }}
          let changelog = '';
          for (const commit of commits) {
            const { id, author, url, message } = commit;
            changelog += `+++\ntitle = "Changelog"\nweight = 99\n+++\n\n`
            changelog += `Commit ${id} by ${author.username}: ${url}\n\n`;
            changelog += `---\n\n`;
            changelog += `${message.replaceAll(/\]\s+\(/gi, "](")}\n\n`;
          }
          fs.writeFileSync('site/content/changelog.md', changelog);
    - name: Build Lexicon Pages
      run: |
        pnpm bf import-lexicon \
          data/languages/hickic/seneran/early-hick/lexicon.jsonld \
          site/content/languages/hick/early-hick/
    - name: Upload changelog as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CHANGELOG.md
        path: site/content/changelog.md
    - name: Build Zola
      uses: shalzz/zola-deploy-action@v0.20.0
      env: 
        BUILD_DIR: site
        BUILD_ONLY: true
    - name: Publish to Cloudflare Pages
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_KEY }}
      run: pnpm run deploy --commit-hash ${{ github.sha }}
      working-directory: site
    - name: Save CHANGELOG.md as an artifact and link it on Discord
      run: echo -ne "${{ github.event.commits[0].message }}" > site/content/changelog.md  
      timeout-minutes: 5
      continue-on-error: true
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.
          See the changes on https://bastion-falls.thekennel.info/changelog/

          
